#!/bin/bash -exu
ROOT="${PWD}"

mkdir -p "${GOPATH}/src/github.com/cloudfoundry"

pushd "${GOPATH}/src/github.com/cloudfoundry" > /dev/null
  ln -s "${ROOT}/bbl-state-resource-src" bbl-state-resource

  pushd bbl-state-resource > /dev/null
    scripts/unit-test
  popd > /dev/null
popd > /dev/null
