#!/bin/bash -exu

rm -rf "${GOPATH}/src/github.com/cloudfoundry"
mkdir -p "${GOPATH}/src/github.com/cloudfoundry"

ROOT="${PWD}"
pushd "${GOPATH}/src/github.com/cloudfoundry" > /dev/null
  ln -s "${ROOT}/bbl-state-resource-src" bbl-state-resource

  pushd bbl-state-resource > /dev/null
    scripts/acceptance-test
  popd > /dev/null
popd > /dev/null
